CHANGELOG.md
README.md
index.js
package.json
tests/index.js

This adds the rule [selector-no-type](http://stylelint.io/user-guide/rules/selector-no-type/) to the config. 
I thought it was in there before, but somehow it got dropped off.

Selector no type

---

README.md
index.js

For code cleanliness, we should not allow units to be specified on `0` values. Reference: http://stylelint.io/user-guide/rules/length-zero-no-unit/
/cc @jonrohan @broccolini

Prevent units in zero values

---

CHANGELOG.md
README.md
index.js
package.json

We have a `selector-class-pattern` rule turned on, but we're in a transition period where the old naming and the new naming don't match. This has led to a lot of disabling in files, so until we're at a point where the new pattern is more prevalent, I'm turning this off.
cc @broccolini

Remove selector-class-pattern rule from config

---

index.js
package.json
tests/index.js

Because stylelint 7.10.1 warning:
Deprecation Warning: 'declaration-block-properties-order'has been deprecated and in 8.0 will be removed. Instead use the community 'stylelint-order' plugin pack. See: https://stylelint.io/user-guide/rules/declaration-block-properties-order/
so I replace declaration-block-properties-order rules (deprecated) by stylelint-order plugin

replace declaration-block-properties-order rules (deprecated) by stylelint-order plugin

---

package-lock.json
package.json

This updates to [stylelint-selector-no-utility v4.0.0](https://github.com/primer/stylelint-selector-no-utility/releases/tag/v4.0.0), which is a breaking change because it requires `@primer/css` as a peer dependency.
We don't have to declare it as a peer dependency here because it's a dev dependency already. I've updated our version to `^12.2.0` just so that we're testing with a recent version.

Release 6.0.0

---

.eslintignore
.gitignore
__tests__/index.js
__tests__/no-override.js
__tests__/utils/index.js
__tests__/utils/setup.js
index.js
jest.config.js
package-lock.json
package.json
plugins/no-override.js
plugins/selector-no-utility.js

🚨**This is a breaking change.** Stylelint configs that reference `primer/selector-no-utility` will need to be updated to use `primer/no-override`, and (depending on the quality of the CSS being linted) there may be lots of errors to fix.
This PR moves [stylelint-selector-no-utility](/primer/stylelint-selector-no-utility) into this repo (as `plugins/no-override.js`), renames it `primer/no-override`, and adds the ability to configure which CSS "bundles" in Primer contain classname selectors (`.mt-6`, `.selected`, etc.) that should be considered _immutable_ and will raise linting errors if they're used to style elements in the linted CSS. In other words:
* If your stylelint config includes:
```js
'primer/no-override': true
```
then the "utilities" bundle (FKA `primer-utilities`) will be …

Import selector-no-utility, make it configurable

---

package-lock.json
package.json

Welp, turns out 6.0.0 was already released, so we're bumping to 7.0.0 with the changes in #27:
* The config now uses `primer/no-override` instead of `primer/selector-no-utility`. See #25 for more info.
* `@primer/css` is now a required peer dependency, because we want this to work with different versions of Primer.
* `primer/no-override` is a new rule that replaces `primer/selector-no-utility` and makes it possible to configure files or directories with options that allow or prevent overrides of selectors from different Primer CSS "bundles". See #25 for more info.
* There are more extensive tests, additional `expect()` matchers, and test utilities that make it easy to set rule options in each test.

Release 7.0.0

---

package.json

This PR makes it so that any version of Primer, also Canary (0.0.0.....) works.

Allow any version of Primer

---

package-lock.json
package.json

chore: upgrade 'stylelint-scss' to 3.10.0 for stylelint v10 support

---

__tests__/no-override.js
plugins/no-override.js

This updates our `primer/no-overrides` rule to focus on class selectors specifically, as including non-class selectors produces a lot of false positives in (_cough_) some large custom CSS codebases. I've also reworked the error messages so that they're easier to read, and so that you can `sort` the output to more easily find what you're looking for:
```python
✖ ".text-gray" should not be overridden in ".foo .text-gray" (found in utilities)
```

Improve primer/no-override to match classes, better reporting

---

__tests__/no-override.js
package-lock.json
package.json
plugins/no-override.js

Release 8.1.0

---

README.md
__tests__/__fixtures__/has-unused-vars.scss
__tests__/__fixtures__/uses-vars.scss
__tests__/no-unused-vars.js
index.js
package-lock.json
package.json
plugins/README.md
plugins/no-unused-vars.js

[:eyes: Check out the plugin docs!](https://github.com/primer/stylelint-config-primer/blob/no-unused-vars/plugins/README.md)
I looked around for stylelint rules to catch unused variables and didn't find any. Of note:
* https://github.com/kristerkari/stylelint-scss/issues/276 was closed and (AFAIK) never addressed
* [`find-unused-sass-variables`](https://github.com/XhmikosR/find-unused-sass-variables) exists, and works! But it's not a stylelint plugin, so we can't really use it here. However, we can use it to check my work on this PR!
Anyway, this adds a `primer/no-unused-vars` stylelint rule that scours all the source files in the optional `files` option (one or more "globs"; the default is `['**/*.scss', '!node_modules']`, so it looks for all `.scss` files that aren't in your node …

Add primer/no-unused-vars

---

README.md
__tests__/__fixtures__/has-unused-vars.scss
__tests__/__fixtures__/uses-vars.scss
__tests__/no-unused-vars.js
__tests__/variables.js
index.js
package-lock.json
package.json
plugins/README.md
plugins/lib/tokens.js
plugins/lib/variable-rules.js
plugins/no-unused-vars.js
plugins/variables.js

Release 8.2.0

---

__tests__/variables.js

Minor fix; enables the `variables` plugin during the "doesn't reject properties we don't care about" test.

Enable variables plugin during test

---

__tests__/borders.js
__tests__/colors.js
__tests__/typography.js
package-lock.json
package.json
plugins/borders.js
plugins/box-shadow.js
plugins/colors.js
plugins/lib/decl-validator.js
plugins/lib/variable-rules.js
plugins/spacing.js
plugins/typography.js

This is the next stage after #50: using data published in a forthcoming version of Primer CSS (see: https://github.com/primer/css/pull/949), this updates the validator logic to find suitable replacements for certain variables. It's kind of confusing to describe, but given the SCSS in Primer:
```scss
$gray-200: #e1e4e8 !default;
$border-gray: $gray-200 !default;
```
And the rule:
```js
module.exports = createVariableRule('primer/borders', {
'border-color': {
values: '$border-*'
}
})
```
A stylelint config with `{rules: {'primer/borders': true}}` will be able to suggest replacements for, and autofix, the following CSS:
```diff
-.foo { border-color: $gray-200; }
+.foo { border-color: $border-gray; }
-.bar { border-color: #e1e4e8; }
+.bar { border-color: $border-gray; }
```
How? Because [the …

Get variable aliases from @primer/css/dist/variables.json

---

__tests__/colors.js
__tests__/spacing.js
__tests__/variable-rules.js
plugins/borders.js
plugins/box-shadow.js
plugins/colors.js
plugins/lib/decl-validator.js
plugins/lib/variable-rules.js
plugins/spacing.js
plugins/typography.js

This is a follow-up for #50 and #52 after doing some testing in Primer CSS. So far, here's the deal:
```js
module.exports = createVariableRule('primer/whatever', ({variables}) => {
/* do something with variables here */
})
```
```js
module.exports = {
extends: 'stylelint-config-primer',
rules: {
'primer/colors': [true, {
rules: ({variables, rules}) => {
/* do something with variables and/or rules here */
return rules
}]
}
})
```

Variable rule fixes

---

__tests__/colors.js
plugins/lib/decl-validator.js
plugins/lib/variable-rules.js

While testing in github/github I noticed that some errors were being reported more than once (sometimes as many as four times!). I traced this back to 48a08b5932b726b44f3be7d3eb700c5f05125eaa, where I changed how the AST was walked to explicitly walk the rules (only) then declarations within those. Turns out, for nested selectors this was causing the nodes to be walked (and then validated) multiple times.
The solution is a [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) that gets an entry for every declaration that's validated, and we skip declarations that are already in it.
While testing the fix for this I also discovered that I'd been mutating the plugin's "base" rules with overrides, so [this particular …

Prevent declarations from being validated more than once

---

CHANGELOG.md
__tests__/borders.js
__tests__/box-shadow.js
__tests__/colors.js
package-lock.json
package.json
plugins/borders.js
plugins/box-shadow.js
plugins/colors.js
plugins/lib/decl-validator.js

To enable [color modes](https://github.com/primer/css/pull/1131) in Primer CSS, we are transitioning from SCSS variables for colors to CSS variables. Our [stylelint config](https://github.com/primer/stylelint-config-primer), however, does not recognize CSS variables, resulting in linting errors.
This PR updates the `primer/colors`, `primer/borders`, and `primer/box-shadow` rules to allow CSS color variables with the correct functional names. For example, `color: var(--color-text-primary)` will no longer cause a linting error.
**Note:** This PR only *adds* support for CSS color variables. It does not remove support for SCSS color variables. Eventually, we will want to update our stylelint config to discourage the use of SCSS color variables, but that should be done in a separate PR. 
We …

Update stylelint config to support CSS variables

---

CHANGELOG.md
package-lock.json
package.json
plugins/no-undefined-vars.js

`primer/no-undefined-vars` was taking a _very_ long time to run in Primer CSS because it was searching for variable definitions in all files every time it linted a file (`O(n^2)` 😱).
This PR caches the defined variable names so we only search for them once.

Cache variable definitions in no-undefined-vars rule

---

package-lock.json
package.json

The new stylelint config was throwing some exception about a transitive dependency from `string.prototype.matchall`; updating it seems to have fixed it.

Update string.prototype.matchall to fix transitive dependency issue

---

__tests__/no-undefined-vars.js
package-lock.json
package.json
plugins/no-undefined-vars.js

This PR fixes `no-undefined-vars` failing for values with fallbacks, e.g. `var(--color-text-primary, #000000)`

Allow CSS variables with fallback values in no-undefined-vars

---

README.md
__tests__/__fixtures__/defines-new-color-vars.scss
__tests__/no-scale-colors.js
__tests__/no-undefined-vars.js
package.json
plugins/README.md
plugins/no-scale-colors.js
plugins/no-undefined-vars.js

This PR adds three features:
1. Updates `no-undefined-vars` to allow variables defined via `@include color-mode-var(...)`. It does this using a second regex in `getDefinedVariables`. The logic hard-codes the name of the mixin, which isn't my favorite and isn't very reusable, but I didn't come up with any great solutions aside from allowing it to be configurable and creating the regex from a string.
2. Updates `no-undefined-vars` to check the two final parameters of the `color-mode-var` mixin to ensure that the values used are defined, if they are CSS values. This change is necessary as the parser seems to only be able to turn the mixin invocation into two parts, the `@include` part and the entire rest of the call, so even when walking the at-rules, this has to be implemented with a few …

Add additional CSS variable/color mode checks

---

.changeset/brown-tigers-buy.md
.changeset/fair-pets-relax.md
__tests__/__fixtures__/defines-new-color-vars.scss
__tests__/no-undefined-vars.js
plugins/no-undefined-vars.js

This PR adds additional `verbose` logging to the `no-undefined-vars` rule to assist with tracking down issues when linting a large codebase. Additionally, it adds handling for the following edge cases:
* Commented out colors (`// --color-my-other-commented-color: #1b1f23;`)
* Commented out `color-mode-var` invocations (`// @include color-mode-var('my-commented-color', ...`)
* Regular declarations with two dashes (`$readme-blue--light: #4f80f9`)

Add additional logging and handle more edges cases

---

.github/workflows/ci.yml

Looks like changeset-bot force-pushes against the release PR it creates, which means it overwrote my changes to `ci.yml`. Luckily Git is awesome, so here they are again.

Reapply lost changes for forcing a prerelease update on every commit

---

.changeset/breezy-brooms-work.md
package-lock.json
package.json

This PR updates `globby` from 9.x to 11.x. Note that it includes `fast-glob` v3, which has [some breaking changes](https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0). I looked over them and none of them seem concerning.

Update globby to 11.0.1

---

.changeset/soft-weeks-film.md
__tests__/borders.js
__tests__/box-shadow.js
__tests__/colors.js
__tests__/spacing.js
__tests__/typography.js
plugins/borders.js
plugins/box-shadow.js
plugins/colors.js
plugins/lib/variable-rules.js
plugins/spacing.js
plugins/typography.js

I think this could be a neat addition that will funnel users to the documentation when they hit errors and warnings.
I just implemented it on the `borders` ruleset but I can add the others before merging if this looks good to y'all.

Add option to add URL to error message

---

index.js

I want to enable [prettier](https://prettier.io/) on `github/github` but it clashes with some formatting rules in stylelint so I would like to remove those rules. I would have overwritten these in the local stylelint config but as far as I can tell, that is not possible 🤔 
I could remove all the [stylistic issues](https://stylelint.io/user-guide/rules/list#stylistic-issues) but I feel like that would be too heavy handed.

Remove rules that clash with prettier

---

README.md

`declaration-block-properties-order` was removed and replaced with [`stylelint-order`](https://github.com/hudochenkov/stylelint-order) in https://github.com/primer/stylelint-config-primer/pull/13. This updates the documentation.

Fix documentation for stylelint-order

---

.changeset/wicked-singers-rule.md
plugins/no-deprecated-colors.js

The goal of this is to add reporting to the linter so we can see how many variables are replaced.
By turning `verbose: true` on in the codebases' stylelint config you can see the report printed out.
The one thing I don't know how to solve is the count keeps printing out as it's climbing. Because the plugin is run for each file, not sure how to tally them. Any ideas would be accepted.

Adding reporting to the linter to know how many variables are replaced

---

.changeset/quiet-mugs-turn.md
__tests__/borders.js
__tests__/colors.js
plugins/borders.js
plugins/colors.js

This fixes the primer/colors and primer/borders rules to be more general with primitive's new css variable naming. 
It would still be nicer to rewrite this to be more explicit and only match variables that exist from primitives. We'd need a system to list all the variables and categorize them.
cc https://github.com/primer/css/pull/1576

Fixing the primer/colors and primer/borders rules

---

.changeset/config.json
.changeset/nervous-geckos-remain.md
.github/workflows/release.yml
.github/workflows/release_canary.yml
.github/workflows/release_candidate.yml
CHANGELOG.md
README.md
__tests__/index.js
package.json
plugins/README.md
plugins/no-override.js

I wanted to rename the package to use our primer org scope. This package was made before we had the org scoping and we never moved it into the main org. 
@colebemis Since you renamed the react package recently, can you help me not forget any important steps in this process?

Renaming the package to use org scope

---

.changeset/famous-ladybugs-report.md
__tests__/__fixtures__/deprecations.json
__tests__/no-deprecated-colors.js
package.json
plugins/no-deprecated-colors.js
yarn.lock

I found that the linter missed this case:
```scss
$border: $border-width $border-style var(--color-border-primary) !default;
```
Because it was only checking css rules, I changed it to walk all declarations, and it picked it up. I also added a test for a nested lint.
```scss
.x { border: 1px solid var(--color-text-primary); .foo { color: var(--color-text-primary); } }
```
And replacing multiple variables in the same row
```scss
.x { border-color: var(--color-border-primary) var(--color-border-secondary); }
```

Updating no-deprecated-colors plugin for edge cases

---

.changeset/mean-pillows-provide.md
index.js

This removes the [scss/dollar-variable-default](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/dollar-variable-default/README.md) rule in the config. 
We had this rule turned on for primer/css, but after pulling in here and testing on our custom css codebase, I think it's better if we don't use it anymore. Especially since primer/css is moving toward using more of primer/primitives.

Truning off scss/dollar-variable-default

---

.changeset/beige-chefs-speak.md
__tests__/spacing.js
plugins/spacing.js

I found that PostCSS's `walkDecl` doesn't walk recursively, so it's missing any declarations nested. I updated the plugin to walk everything and filter out what isn't `padding|margin`. 
✅ Tests added
```scss
.foo {
padding: 2px; // It catches this
.bar {
padding: 2px; // but not this
}
}
```

Fixing an issue where the new spacing plugin isn't traversing child sectors.

---

.changeset/tender-eggs-rhyme.md
__tests__/spacing.js
package.json
plugins/spacing.js

This PR fixes a case that was missing from the spacing plugin. In this example, the linter should fail on `6px` because it's separate from the math group happening.
I rewrote the walk function to recursively dive into each function group and evaluate the variables. This gives us more reliable results.
```scss
// This failed to be picked up by the linter before.
.x {
padding: 6px ($spacer-3 + 12px + $spacer-2);
}
```

Making linter pick up separate function groups

---

.changeset/dull-glasses-visit.md
__tests__/spacing.js
plugins/spacing.js

I found when upgrading that the last release was missing values with dots in them like `0.5` https://github.com/primer/css/pull/1956/files#diff-fe986252765f6a97978946e9a32e8946b267ea06df7534f06dc47c1c6578d94bL147
This adds 2 tests, and fixes the bug

[Bug fix] Catching values with dots in them

---

.changeset/clean-seas-mate.md
README.md
__tests__/responsive-widths.js
index.js
plugins/README.md
plugins/responsive-widths.js

This PR creates a new plugin that will throw an error when we're using `width` or `min-width` with a size that's larger than our minimum browser size. This is because it could cause problems with responsive pages.
closes https://github.com/github/primer/issues/741
```css
/* pass */
.foo {
max-width: 800px;
}
.foo {
width: 20px;
}
/* fail */
.foo {
width: 800px;
}
.foo {
min-width: 800px;
}
```

Creating a responsive-widths plugin to keep fixed widths smaller than the minimum viewport size

---

.changeset/large-lemons-arrive.md
__tests__/utilities.js
plugins/utilities.js

I was noticing that the plugin was missing some cases in practice. For example it would miss the `.foo` class in the example below.
```scss
body {
font-size: 12px;
}
.foo {
margin-top: $spacer-1;
}
```
[Example in code](https://github.com/github/github/blob/261186ffa9a04f916c0c1ee7f4b3f26c956b64ff/app/assets/stylesheets/bundles/github/integrations.scss#L16)
This was because of the `return false` in my selector check. This was stopping the processing of the rest of the page when it happened. 
I added a test case for this bug.

Fixing issue in utilities plugin

---

.changeset/cold-cooks-taste.md
__tests__/no-undefined-vars.js
plugins/no-undefined-vars.js

This expands the `no-undefined-vars` rule to allow for variables that are defined in a local scope, like:
```css
.x {
--color-foo: #ffeeee;
color: var(--color-foo);
}
```
This allows developers to use variables defined in locally scoped components, which can be useful for imperatively altering them using the JavaScript APIs, without changing the specific properties they are referred in. So for example this can be useful when using calc or min/max for a specific component:
```css
.x {
--min-margin: 100px;
margin-bottom: max(--min-margin, 1vh);
}
```
```js
// allows for changing minimum value without overriding actual value
embiggen.addEventListener('click', () => $('.x').setProperty('--min-margin', '200px'))
```
However this _does not allow_ for undefined vars of a different scope:
```css …
```

allow for vars defined in scope, or within :root/:host selectors in file

---

.changeset/odd-needles-confess.md
__tests__/no-deprecated-colors.js
package.json
plugins/lib/primitives-v8.json
plugins/no-deprecated-colors.js

Removes the inline var like `color: var(--fgColor-default, var(--color-fg-default));` in favor of adding fallbacks in with PostCSS at build time.

Remove inline fallback var for no-deprecated-colors

---

.changeset/slimy-files-relate.md
plugins/lib/primitives-v8.json

`inset` is back! This adds it as a proper fallback.

Add `bgColor-inset` fallback for Primitives v8

---

.changeset/beige-cobras-reflect.md
__tests__/new-color-vars-have-fallback.js
index.js
plugins/new-color-vars-have-fallback.js

Adds a new plugin to ensure that new color CSS vars have a fallback value (temporary while we test)

New plugin: `new-color-vars-have-fallback`

---

.changeset/cyan-bugs-cross.md
__tests__/__fixtures__/color-vars.scss
__tests__/no-display-colors.js
index.js
plugins/no-display-colors.js

Adds a rule to disallow new `display` color tokens while they are being actively developed.

New rule: safegaurd `display` color tokens

---

__tests__/spacing.js
package-lock.json
plugins/spacing.js

Update the link for errors in the spacing plugin to use the new path.

Update link for spacing plugin

---

.gitignore
package-lock.json
package.json
rollup.config.js

Add a bundle step to the package to emit ESM and CommonJS entry points. These are referenced in the `exports` config in `package.json` under the `import` and `require` conditions, respectively.

feat(bundle): add rollup for emitting CommonJS and ESM

---

.changeset/giant-kangaroos-provide.md
__tests__/__fixtures__/good/example.module.css
index.js

Allow css nesting in stylelint config for `*.module.css` files

Update config to alloy nesting in css modules

---

.changeset/clean-ads-work.md
__tests__/__fixtures__/good/example.module.css
index.js
package-lock.json
package.json

Adds a new Stylelint rule for CSS modules: [`css-modules/no-global-scoped-selector`](https://github.com/lmichelin/stylelint-css-modules-no-global-scoped-selector). This ensures that all selectors in a CSS module file are locally scoped - that is, they fall underneath a class selector that will be hashed. 
The point of CSS modules is to encapsulate styles, so global selectors directly violate that principle. By enforcing encapsulation we can ensure that components minimize their side effects on the rest of the page. I think it's a good idea to start enforcing this early to teach best practices in the beginning.
From the docs:
> _:white_check_mark: Example of local-scoped selectors:_
> 
> ```scss
> // SCSS
> 
> .container {
>   // ...
> }
> 
> .container {
>   :global .external-class {
> …
```

Add "no global scoped selector" rule for CSS Modules

---

__tests__/__fixtures__/good/example.module.css

We don't want to encourage use of `--space-x`

Remove --space from example.module.css

---

.changeset/clean-ads-work.md
__tests__/__fixtures__/good/example.module.css
index.js
package-lock.json
package.json

Reverting https://github.com/primer/stylelint-config/pull/414
This is because the dependencies from that plugin are outdated and causing security concerns. Hopefully if the dependencies are updated in the future we can revisit the plugin.

Revert global scope plugin

---

.changeset/weak-walls-stare.md
__tests__/typography.js
index.js
plugins/typography.js

Closes https://github.com/github/primer/issues/4009
This PR adjusts the rule set in the following ways:
- `font-style` should allow keywords, `italic, normal`
- border should allow `none` https://stylelint.io/user-guide/rules/declaration-property-value-disallowed-list
- Update autofix in typography to always replace with the first suggestion

Stylelint fixes based on feedback

---

.changeset/cold-beers-warn.md
index.js
package-lock.json
package.json

The problem is our caniuse db is out of date and it's saying we can't use features that we can. I found that the plugin we're using isn't making updates anymore https://github.com/RJWadley/stylelint-no-unsupported-browser-features/issues/299
So I found another plugin that does the same thing. This rule will remain a warning. https://github.com/3846masa/stylelint-browser-compat

Removing no-unsupported-browser-features and replacing with browser-compat

---

.changeset/polite-carrots-pay.md
package-lock.json
package.json
plugins/lib/utils.js

This updates to Primtives v10 release candidate and makes fixes that will be necessary based on dictionary changes.
**Note:** I'm adding `@primer/primitives` as a devDependency so that the build will not be ambiguous as to which version to test. This won't change any dependency graph in dotcom.

Making fixes for primitives v10 rc
